name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14" # Set this to the node version you are using

      - name: Install Dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy

      - name: Manual Deployment
        run: |
          git config --global user.name 'Akash Mishra'
          git config --global user.email 'sleepythread@gmail.com'
          git checkout -b gh-pages
          git add -f build/*
          git commit -m "Deploying to gh-pages"
          git push origin gh-pages --force
